/*
    GETDATE DATEDIFF DATENAME DATEPART DATEADD
    ISNULL
    CAST CONVERT
    CHARINDEX
*/
--SELECT
    SELECT -- projeção
        ID, ACAO, ISNULL(DESCRICAO, 'SEM DESCRIÇÃO') AS 'DESCRICAO', DATAHORA, DATEDIFF(DAY, DATAHORA, GETDATE()) AS 'DIAS PASSADOS'
    FROM -- origem
        LOG
    WHERE -- seleção
        ACAO IS NOT NULL -- Não utilizar `CAMPO_VAZIO = NULL`
        AND DESCRICAO LIKE '%erro%'
    ORDER BY 
        ACAO DESC, DATAHORA ASC
    GO

    SELECT
        CAST(DESCRICAO AS VARCHAR),
        CONVERT(DATAHORA, DATETIME, 105)
    FROM
        LOG
    GO

--UPDATE
    UPDATE LOG
    SET DESCRICAO = 'Atualização de descrição'
    WHERE ID = 1
    GO 

--DELETE
    DELETE FROM LOG
    WHERE ID = 2
    GO