/*
    GETDATE DATEDIFF DATENAME DATEPART DATEADD
    ISNULL
    CAST CONVERT
    CHARINDEX
*/

SELECT 
    ID, ACAO, ISNULL(DESCRICAO, 'SEM DESCRIÇÃO') AS 'DESCRICAO', DATAHORA, DATEDIFF(DAY, DATAHORA, GETDATE()) AS 'DIAS PASSADOS'
FROM 
    LOG
WHERE
    ACAO IS NOT NULL
ORDER BY ACAO DESC, DATAHORA ASC
GO

SELECT
    CAST(DESCRICAO AS VARCHAR),
    CONVERT(DATAHORA, DATETIME, 105)
FROM
    LOG
GO