-- COMANDOS BÁSICOS DE SQL
SHOW DATABASES; /* LISTA DE BASES DE DADOS */
CREATE DATABASE NOME_DA_BASE; /* CRIA UMA NOVA BASE DE DADOS */
USE NOME_DA_BASE; /* SELECIONA A BASE DE DADOS */
DROP DATABASE NOME_DA_BASE; /* DELETA A BASE DE DADOS */
SHOW TABLES; /* LISTA DE TABELAS NA BASE DE DADOS ATUAL */

-- CONSULTA EXEMPLO
SELECT COLUNA_1, COLUNA_2 /* PROJEÇÃO */
FROM TABELA /* ORIGEM */
JOIN TABELA_2 /* JUNÇÃO */
    ON TABELA.COLUNA_COMUM = TABELA_2.COLUNA_COMUM; /* CONDIÇÃO DE JUNÇÃO */
WHERE COLUNA_1 = 'VALOR' /* FILTRO */
GROUP BY COLUNA_1 /* AGRUPAMENTO */
HAVING COUNT(COLUNA_2) > 5 /* FILTRO APÓS AGRUPAMENTO */
ORDER BY COLUNA_1 DESC /* ORDENAÇÃO */
LIMIT 10; /* LIMITA O NÚMERO DE REGISTROS RETORNADOS */

-- FUNÇÃO DE TRATAMENTO DE VALORES NULOS
IFNULL(COLUNA, 'VALOR_PADRÃO') /* FUNÇÃO DE TRATAMENTO DE VALORES NULOS */